// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mrdolev/sieve-hll-go/internal/collector (interfaces: CollectorI)
//
// Generated by this command:
//
//	mockgen -destination ./mocks/collector.go -package mocks github.com/mrdolev/sieve-hll-go/internal/collector CollectorI
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCollectorI is a mock of CollectorI interface.
type MockCollectorI struct {
	ctrl     *gomock.Controller
	recorder *MockCollectorIMockRecorder
	isgomock struct{}
}

// MockCollectorIMockRecorder is the mock recorder for MockCollectorI.
type MockCollectorIMockRecorder struct {
	mock *MockCollectorI
}

// NewMockCollectorI creates a new mock instance.
func NewMockCollectorI(ctrl *gomock.Controller) *MockCollectorI {
	mock := &MockCollectorI{ctrl: ctrl}
	mock.recorder = &MockCollectorIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCollectorI) EXPECT() *MockCollectorIMockRecorder {
	return m.recorder
}

// Enqueue mocks base method.
func (m *MockCollectorI) Enqueue(ip string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Enqueue", ip)
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockCollectorIMockRecorder) Enqueue(ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockCollectorI)(nil).Enqueue), ip)
}

// Close mocks base method.
func (m *MockCollectorI) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockCollectorIMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockCollectorI)(nil).Close))
}
