// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mrdolev/sieve-hll-go/internal/ip_stats (interfaces: IPStatsServiceI)
//
// Generated by this command:
//
//	mockgen -destination ./mocks/service.go -package mocks github.com/mrdolev/sieve-hll-go/internal/ip_stats IPStatsServiceI
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIPStatsServiceI is a mock of IPStatsServiceI interface.
type MockIPStatsServiceI struct {
	ctrl     *gomock.Controller
	recorder *MockIPStatsServiceIMockRecorder
	isgomock struct{}
}

// MockIPStatsServiceIMockRecorder is the mock recorder for MockIPStatsServiceI.
type MockIPStatsServiceIMockRecorder struct {
	mock *MockIPStatsServiceI
}

// NewMockIPStatsServiceI creates a new mock instance.
func NewMockIPStatsServiceI(ctrl *gomock.Controller) *MockIPStatsServiceI {
	mock := &MockIPStatsServiceI{ctrl: ctrl}
	mock.recorder = &MockIPStatsServiceIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPStatsServiceI) EXPECT() *MockIPStatsServiceIMockRecorder {
	return m.recorder
}

// Collect mocks base method.
func (m *MockIPStatsServiceI) Collect(ctx context.Context, ip string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Collect", ctx, ip)
}

// Collect indicates an expected call of Collect.
func (mr *MockIPStatsServiceIMockRecorder) Collect(ctx, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collect", reflect.TypeOf((*MockIPStatsServiceI)(nil).Collect), ctx, ip)
}
